### ISSUE TITLE
Change selection background colors

### ISSUE THREAD

**Issue by linted** [httpsterio/vscode-arctic#9]
Hey, I love this theme, the colors work really nice together. The only real problem that I have with it is that it can be difficult to see words getting highlighted when selected or searched for. Currently the color seems to be a dark grey which is difficult to discern on the black background. I think it would be nice to see it changed to either a dark red or green, just to make it stand out a little more. 
I think the setting might be `editor.selectionBackground`

**Comment by httpsterio** [comment]
Hey, thanks for your issue.

You are correct, as a theme where I wanted to focus on accessibility and legibility, it definitely falls short on that part. It's a problem I haven't had time to solve to be honest. 

The problem is that VSCode doesn't support editor.selectionForeground for "low contrast" themes, ie. themes that are not in high contrast mode. This means that when selecting or highlighting texts, it'll retain its' original coloring determined in the theme = finding a background color for the selection that  works with all of the token colors is near impossible.

Currently, I have no proper solution to this except for having the selectionBackground as #000 and lightening the editor background a bit to make it stand out against it.

I will however look into if changing the whole theme into a high contrast theme and if it'll have any unwanted side effects, as it would enable me to fix the highlight colors.

This issue has been reported by many other theme developer as well but currently that's basically the only fix available.

**Comment by httpsterio** [comment]
Hey, finally got around to push the update. Its up on the store. Thanks a bunch @linted !
